name: sign_in_with_apple_native
description: "A Flutter plugin for iOS 13+ that enables you to use native 'Sign in with Apple' functionality."
version: 0.0.1
homepage: https://github.com/ionesoftware/sign_in_with_apple_native_ios

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SignInWithAppleNativePlugin
